apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: hello-web1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-world 
  template:
    metadata:
      labels:
        app: hello-world                 # Pod labels
    spec:
      containers:
      - name: hello-ctr
        image: nigelpoulton/k8sbook:latest
        ports:
        - containerPort: 8080
